# Application Configuration
---
# Application section

# Top level New Relic configuration. This will be applied to all flow below. Individual flows can override
# any or all of these setting within the specific flow. See below for details.
newrelic:
  # required
  account_id: <NEW_RELIC_ACCOUNT_ID>
  # required
  api_key: <NEW_RELIC_API_KEY>

# Top level kafka configuration. This will be applied to all flows below. Individual flows can override
# any or all of these setting within the specific flow. See below for details.
#
# The 'group.id' property is automatically set to `newrelic_{TOPIC_NAME}
#
# NOTE: Additional properties can be passed to kafka by listing them below.
#   Underscores (_) will be converted to periods (.) when the configuration is read.
#     for example: ssl_client_auth, would be passed to kafka as, 'ssl.client.auth'
kafka:
  #required
  bootstrap_servers: localhost:9092
  # optional (defaults to newrelic_{TOPIC_NAME})
  # group.id: <DEFAULT_CUSTOM_EVENT_TYPE>
  # these usually do not need to be changed
  # max_poll_interval_ms: 600000
  # max_poll_records: 50
  key_deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value_deserializer: org.apache.kafka.common.serialization.StringDeserializer
  auto_commit_interval_ms: 1000
  enable_auto_commit: true

# List of flows. A flow represents:
#  - a kafka topic / partition to read from
#  - a transformer class
flows:
  - kafka_topic: <KAFKA_TOPIC>
    # set to 'all' for all partitions, or a numbered list, '1, 2, 3, 4'
    partition_list: all
    # optional defaults to topic name. Only used for custom events.
#    custom_event_type: <INSIGHTS_CUSTOM_EVENT_TYPE>
    transform_class: com.newrelic.es.transform.JsonFlattenFunction

# optional - proxy information for connecting to New Relic.
#http_proxy:
#  hostname: localhost
#  port: 8080
#  scheme_name: http

# optional - sends a test message to new relic and exits, does not read any customer data.
#   Useful for testing connectivity to New Relic API servers without sending data.
test_and_exit: false

# Performance tuning options
# optional - sets size of the application internal queues for processing.
#   Not related to kafka.
queue_size: 1000

# You can override the top level 'kafka' or 'newrelic' sections in the flow section.
# For example if you had a flow using a topic on a different bootstrap_server, you can
# add that to that specific flow. We'll also send this to another newrelic account with api key.
# Example:
#
# newrelic:
#  account_id: 000000
#  api_key: ABC...123
#
# kafka:
#  bootstrap_servers: localhost:9092
#
# flows:
#  - kafka_topic: topic3
#    transform_class: com.iarad.transformer.MetricEventTransformer
#    kafka:
#      bootstrap_servers: anotherhost:9092
#    newrelic:
#      account_id: 111111
#      api_key: XYZ...123
#
# If nothing is overridden in the flows section, it will populate these fields with the
# top level values.

