---
name: "release"

on:
  create:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        working-directory: newrelic-kafka-connector
        run: mvn -B clean package --file pom.xml
      - name: Set Vars
        id: vars
        run: |
          pat="-rc-[0-9]+$"
          if [[ $GITHUB_REF =~ $pat ]]; then prerel="true"; else prerel="false"; fi
          echo "::set-output name=is_prerelease::${prerel}"
      - name: "Auto Release"
        uses: "marvinpinto/action-automatic-releases@v1.2.0"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: ${{ steps.vars.outputs.is_prerelease }}
          files: |
            newrelic-kafka-connector/target/components/packages/*.zip